# Generated by Django 4.2 on 2023-04-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("special_status", "can read all books")]},
        ),
    ]
